server:
  port: 8081
  #error:
   # whitelabel:
    #  enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportPortal
    password: Chennai@330
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      hibernate:
        format_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: klintontechnical@gmail.com
    password: elmsagdkxzptpwjz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

    #mvc:
  # throw-exception-if-no-handler-found: true
  #web:
   # resources:

jwt:
  secret: hari3030



